graph_pkl_filename: '../STGNN/metrla/DCRNN/data/adj_mx.pkl'
batch_size: 16
num_nodes: 207
num_rnn_layers: 2
rnn_units: 64
seq_len: 12
output_dim: 1
enc_input_dim: 2
max_diffusion_step: 2
filter_type: 'dual_random_walk'
dec_input_dim: 1




